apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: elasticsearch
    org: org2
  name: elasticsearch-org2
spec:
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
  selector:
    name: elasticsearch
    org: org2