apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: org2-es1
  labels:
      name: elasticsearch
      org: org2
      instance: es1
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      name: elasticsearch
      org: org2
      instance: es1
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: elasticsearch
        org: org2
        instance: es1
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xmx512m -Xms512m
        - name: cluster.name
          value: ORG2Cluster
        - name: path.data
          value: /usr/share/nfsShare/es1/data
        - name: path.logs
          value: /usr/share/nfsShare/es1/logs
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
        name: elasticsearch
        volumeMounts:
        - name: nfsvol
          mountPath: /usr/share/nfsShare
        ports:
        - containerPort: 9200
        resources: {}
      volumes:
        - name: nfsvol
          persistentVolumeClaim:
            claimName: nfs-claim1-org2
      restartPolicy: Always
status: {}
