apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: kibana
    org: org2
  name: kibana-org2
spec:
  ports:
  - name: "5601"
    port: 5601
    targetPort: 5601
    nodePort: 31525
  selector:
    name: kibana
    org: org2
  type: NodePort
