apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: logstash
    org: org2
  name: logstash-org2
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    nodePort: 31523
  selector:
    name: logstash
    org: org2