apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  labels:
    name: kibana
    org: org1
data:
  kibana.yml: |-
    ---
    server.name: kibana-es1
    server.host: "0"
    elasticsearch.url: http://elasticsearch-org1:9200
    ## Disable X-Pack
    ## see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
    ##     https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-enabling
    #
    xpack.security.enabled: false
    xpack.monitoring.enabled: false
    xpack.graph.enabled: false
    xpack.reporting.enabled: false
    xpack.ml.enabled: false
    xpack.watcher.enabled: false