apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: kibana
    org: org1
  name: kibana-org1
spec:
  ports:
  - name: "5601"
    port: 5601
    targetPort: 5601
    nodePort: 31515
  selector:
    name: kibana
    org: org1
  type: NodePort
