apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: logstash
    org: org1
  name: logstash-org1
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    nodePort: 31512

  selector:
    name: logstash
    org: org1